### PR TITLE
fix: add window postMsg to get base64 on new android

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Review by tlvince — COMMENTED** [review]
Can't test this on a device right now, but code lgtm. Could you perhaps explain in a comment/readme what has changed in newer Android versions and why this is needed? Also, I think this needs to be merged into the [init-workaround](https://github.com/fielded/react-native-signature-pad/tree/init-workaround) branch, or a new branch with them combined; init-workaround is used to set the initial canvas size.

**Comment by freefony** [comment]
Any reason not to merge both into master?
> Also, I think this needs to be merged into the init-workaround branch, or a new branch with them combined; init-workaround is used to set the initial canvas size.

**Comment by freefony** [comment]
I honestly don't have the details of this other than the `onChange` event would not fire on new android devices. Not much help from the issue raised on the repo about this but i will ask

>Could you perhaps explain in a comment/readme what has changed in newer Android versions and why this is needed?

**Comment by tlvince** [comment]
`master` is generally kept in sync with upstream for easier pulls

**Comment by freefony** [comment]
ok. `develop` it is then

**Pull request closed without merging**
